### ISSUE TITLE
assets do not compile with jquery-ui-rails 6.0.0

### ISSUE THREAD

**Issue by cemeyer2** [randoum/gridstack-js-rails#3]
when i bundle updated and got `jquery-ui-rails 6.0.0`, my assets would not compile due to a missing `jquery-ui/mouse`. I worked around this by pinning the version of `jquery-ui-rails` to `5.0.5` in my `Gemfile`.

**Comment by randoum** [comment]
gridstack-js-rails is just a wrapper, your issue is coming from jquery-ui-rails or gridstack.js 

Though it seems that jquery-ui-rails changed their assets paths. Try to create a shortcut of `jquery-ui/mouse` to `jquery-ui/widgets/mouse`
